### ISSUE TITLE
New emotes

### ISSUE THREAD

**Issue by NecroTM** [KlutzyBubbles/lc-better-emotes#15]
I don´t know how much hassle is it, but would it be possible to add the new emotes the original mod added? Like the writing board, Russian dance, and secondary moves on certain emotes?

**Comment by KlutzyBubbles** [comment]
I did originally try in this branch https://github.com/KlutzyBubbles/lc-better-emotes/tree/moreemotes-1.3.1

However i gave it a break because there were just so many changes. Now that multiple people have suggested it i might continue BUT MoreEmotes is so close (feature wise) to this mod that there is nearly no need for this mod to exist.

For anyone that stumbles on this issue and it still isnt resolved, i am looking for help with redoing all the emotes to allow for walking while emoting but need some help. If you or anyone you know can help feel free to contact me in anyway.

**Comment by KlutzyBubbles** [comment]
For anyone that comes across this looking for updates, i have the russian dance, implemented however i am now stuck at the sign emote and might give it a crack on the weekend. After that i will need to do more fleshed out testing and then i will consider merging the changes.

**Comment by KlutzyBubbles** [comment]
> I don´t know how much hassle is it, but would it be possible to add the new emotes the original mod added? Like the writing board, Russian dance, and secondary moves on certain emotes?

[v1.4.0](https://github.com/KlutzyBubbles/lc-better-emotes/releases/tag/v1.4.0) Adds these new emotes, thunderstore should also have the update listed
