### ISSUE TITLE
[Dependency deprecated] RuntimeNetcodeRPCValidator

### ISSUE THREAD

**Issue by CoolLKKPS** [KlutzyBubbles/lc-better-emotes#30]
@KlutzyBubbles https://github.com/wwwDayDream/RuntimeNetcodeRPCValidator

**Comment by Ludmuterol** [comment]
https://github.com/wwwDayDream/RuntimeNetcodeRPCValidator/issues/5#issuecomment-2044056838
found this comment by the original maintainer about using https://github.com/EvaisaDev/UnityNetcodePatcher instead

**Comment by KlutzyBubbles** [comment]
> [wwwDayDream/RuntimeNetcodeRPCValidator#5 (comment)](https://github.com/wwwDayDream/RuntimeNetcodeRPCValidator/issues/5#issuecomment-2044056838) found this comment by the original maintainer about using https://github.com/EvaisaDev/UnityNetcodePatcher instead

I have looked into this, it would take a bit more tweaking with the build pipeline for the mod. This is something i want to do, but with the mod still working fine (i believe it was deprecated because of the lack of full support for features, features which this mod doesn't rely on) i will be leaving it as is until new network features are required or it will be known to break.

Unfortunately i am not coding for this mod for the foreseeable future, but am always here to merge in any code that others want to contribute.

I will be happy to give full credit and help to anyone interested in giving the switch over a shot.
